from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
OUT = RESULTS / "private_telemetry_router_decision_policy.csv"


ROWS = [
    {
        "semantic_trigger": "iid scalar stuck-at points",
        "required_evidence": "independent point faults or validation rows where temporal persistence is absent",
        "compatibility_set": "PrivSAF mixture",
        "selection_metric": "validation AUPRC, runtime reported separately",
        "selected_operator": "PrivSAF mixture",
        "evidence_files": "results/icde_revision_detection_summary.csv; results/private_telemetry_cleaning_router_summary.csv",
        "audit_rule": "select mixture posterior when iid stuck-at labels are pointwise and the stuck-column model is compatible",
    },
    {
        "semantic_trigger": "persistent scalar stuck-at or flatline segments",
        "required_evidence": "contiguous scalar constant/flatline labels, native flatline windows, or straight-string labels",
        "compatibility_set": "PrivSAF-HMM; PrivSAF-HMM scan",
        "selection_metric": "validation AUPRC, runtime reported separately",
        "selected_operator": "PrivSAF-HMM",
        "evidence_files": "results/icde_revision_detection_summary.csv; results/native_flatline_method_audit.csv; results/hadisd_multistation_streak_pmldp_rollup.csv",
        "audit_rule": "select HMM posterior when persistence is part of the label semantics and HMM is best within the compatible set",
    },
    {
        "semantic_trigger": "official flat-tolerance labels with scalar values preserved",
        "required_evidence": "public rows contain the scalar value and official flat-tolerance label in the same row",
        "compatibility_set": "PrivSAF-HMM; PrivSAF range-HMM; report frequency; channel GLR",
        "selection_metric": "case-mean AUPRC under frozen KRR-LDP protocol",
        "selected_operator": "PrivSAF range-HMM",
        "evidence_files": "results/coops_verified_flat_full_protocol_summary.csv; results/coops_verified_flat_full_protocol_tier_summary.csv",
        "audit_rule": "select range-HMM when official flat-tolerance labels align with raw flatness and range-HMM leads private baselines",
    },
    {
        "semantic_trigger": "deployed field-QC stuck labels encoding local regime changes",
        "required_evidence": "validation rows show local channel statistic exceeds global stuck-column posterior",
        "compatibility_set": "PM-window GLR; LLR-CUSUM; PrivSAF-HMM",
        "selection_metric": "validation AUPRC inside deployed-QC stratum",
        "selected_operator": "PM-window GLR or LLR-CUSUM",
        "evidence_files": "results/iors_stuck_qc_pmldp_summary.csv; results/iors_stuck_qc_loweps_summary.csv",
        "audit_rule": "route to local channel statistic when the stuck label marks a local QC regime rather than one stuck bucket",
    },
    {
        "semantic_trigger": "row-level prepared multivariate stuck labels",
        "required_evidence": "row labels combine prepared stuck indicators rather than one scalar stuck bucket",
        "compatibility_set": "PM-window GLR; PM-column likelihood scan; PrivSAF-HMM",
        "selection_metric": "validation AUPRC inside row-label stratum",
        "selected_operator": "PM-window GLR",
        "evidence_files": "results/wsn_stuck_labeled_pmldp_summary.csv",
        "audit_rule": "route to window statistic when row-level labels are not generated by a single scalar stuck bucket",
    },
    {
        "semantic_trigger": "explicit availability or dropout labels",
        "required_evidence": "missing/availability symbol is represented in the report alphabet",
        "compatibility_set": "dropout HMM",
        "selection_metric": "validation AUPRC for availability labels",
        "selected_operator": "dropout HMM",
        "evidence_files": "results/iors_dropout_qc_pmldp_summary.csv; results/private_telemetry_cleaning_router_summary.csv",
        "audit_rule": "select dropout emission model when the observed state is availability rather than a scalar stuck value",
    },
]


def main() -> None:
    OUT.parent.mkdir(exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as fout:
        writer = csv.DictWriter(fout, fieldnames=list(ROWS[0]))
        writer.writeheader()
        writer.writerows(ROWS)
    print(f"wrote {OUT} rows={len(ROWS)}")


if __name__ == "__main__":
    main()
