-- Relational schema for the private telemetry cleaning pipeline.
-- The workload is generated by scripts/run_private_telemetry_pipeline_queries.py.

CREATE TABLE reports (
    report_id INTEGER PRIMARY KEY,
    device_id INTEGER NOT NULL,
    ts INTEGER NOT NULL,
    report_bucket INTEGER NOT NULL,
    epsilon REAL NOT NULL,
    mechanism_id TEXT NOT NULL,
    calibration_version TEXT NOT NULL
);

CREATE TABLE mechanism_weights (
    mechanism_id TEXT NOT NULL,
    epsilon REAL NOT NULL,
    report_bucket INTEGER NOT NULL,
    stuck_bucket INTEGER NOT NULL,
    logp_normal REAL NOT NULL,
    logp_fault REAL NOT NULL,
    PRIMARY KEY (mechanism_id, epsilon, report_bucket, stuck_bucket)
);

CREATE TABLE router_policy (
    operator TEXT PRIMARY KEY,
    semantic_layer TEXT NOT NULL,
    output_relation TEXT NOT NULL,
    privacy_effect TEXT NOT NULL
);

CREATE TABLE cleaning_records (
    report_id INTEGER PRIMARY KEY,
    device_id INTEGER NOT NULL,
    ts INTEGER NOT NULL,
    operator TEXT NOT NULL,
    posterior REAL NOT NULL,
    stuck_bucket INTEGER,
    fault_ratio REAL NOT NULL,
    action TEXT NOT NULL,
    repair_value REAL,
    provenance_version TEXT NOT NULL
);

CREATE TABLE provenance_edges (
    output_report_id INTEGER NOT NULL,
    source_table TEXT NOT NULL,
    source_key INTEGER NOT NULL,
    transform TEXT NOT NULL,
    mechanism_id TEXT NOT NULL,
    calibration_version TEXT NOT NULL
);

CREATE TABLE privacy_ledger (
    device_id INTEGER PRIMARY KEY,
    reports INTEGER NOT NULL,
    epsilon_sum REAL NOT NULL,
    device_budget REAL NOT NULL,
    remaining_budget REAL NOT NULL
);

CREATE INDEX idx_reports_device_ts
ON reports(device_id, ts);

CREATE INDEX idx_reports_channel
ON reports(mechanism_id, epsilon, report_bucket);

CREATE INDEX idx_cleaning_action
ON cleaning_records(action, posterior);

CREATE INDEX idx_cleaning_device_ts
ON cleaning_records(device_id, ts);

CREATE INDEX idx_provenance_key
ON provenance_edges(output_report_id);

CREATE TABLE mv_report_counts AS
SELECT mechanism_id, epsilon, report_bucket, COUNT(*) AS n
FROM reports
GROUP BY mechanism_id, epsilon, report_bucket;

CREATE TABLE candidate_likelihoods AS
SELECT
    c.mechanism_id,
    c.epsilon,
    w.stuck_bucket,
    SUM(c.n * w.logp_fault) AS fault_loglik,
    SUM(c.n * w.logp_normal) AS normal_loglik,
    SUM(c.n * (w.logp_fault - w.logp_normal)) AS llr
FROM mv_report_counts c
JOIN mechanism_weights w
  ON w.mechanism_id = c.mechanism_id
 AND w.epsilon = c.epsilon
 AND w.report_bucket = c.report_bucket
GROUP BY c.mechanism_id, c.epsilon, w.stuck_bucket;

CREATE INDEX idx_candidate_llr
ON candidate_likelihoods(epsilon, llr DESC);

CREATE TABLE privacy_budget_trace AS
SELECT
    report_id,
    device_id,
    ts,
    epsilon,
    cumulative_epsilon,
    1000.0 - cumulative_epsilon AS remaining_budget
FROM (
    SELECT
        report_id,
        device_id,
        ts,
        epsilon,
        SUM(epsilon) OVER (
            PARTITION BY device_id
            ORDER BY ts
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_epsilon
    FROM reports
);

CREATE INDEX idx_budget_trace_device_ts
ON privacy_budget_trace(device_id, ts);

CREATE INDEX idx_budget_remaining
ON privacy_budget_trace(remaining_budget, device_id, ts);

CREATE TABLE hourly_cleaned_analytics AS
SELECT
    r.device_id,
    r.ts / 60 AS hour_id,
    COUNT(*) AS reports,
    AVG(c.posterior) AS avg_fault_posterior,
    SUM(CASE WHEN c.action = 'repair' THEN 1 ELSE 0 END) AS repaired_reports,
    AVG(CASE WHEN c.action = 'repair'
             THEN c.repair_value
             ELSE (2.0 * r.report_bucket / 31.0) - 1.0 END) AS cleaned_mean
FROM reports r
JOIN cleaning_records c USING(report_id)
GROUP BY r.device_id, r.ts / 60;

CREATE INDEX idx_hourly_device_hour
ON hourly_cleaned_analytics(device_id, hour_id);

CREATE TABLE cleaned_event_windows AS
SELECT
    c.device_id,
    c.ts / 60 AS hour_id,
    MIN(c.ts) AS start_ts,
    MAX(c.ts) AS end_ts,
    COUNT(*) AS flagged_reports,
    AVG(c.posterior) AS avg_posterior,
    GROUP_CONCAT(DISTINCT p.semantic_layer) AS routed_semantics
FROM cleaning_records c
JOIN router_policy p ON p.operator = c.operator
WHERE c.action IN ('flag', 'repair')
GROUP BY c.device_id, c.ts / 60
HAVING COUNT(*) >= 2;

CREATE INDEX idx_event_windows_device_hour
ON cleaned_event_windows(device_id, hour_id);

CREATE TABLE repair_uncertainty_analytics AS
SELECT
    r.device_id,
    r.ts / 60 AS hour_id,
    COUNT(*) AS reports,
    AVG(CASE WHEN c.action = 'repair'
             THEN c.repair_value
             ELSE (2.0 * r.report_bucket / 31.0) - 1.0 END) AS cleaned_mean,
    AVG((2.0 * r.report_bucket / 31.0) - 1.0) AS unrepaired_mean,
    AVG(c.posterior * (1.0 - c.posterior)) AS uncertainty_proxy,
    SUM(CASE WHEN c.action = 'repair' THEN 1 ELSE 0 END) AS repair_count
FROM reports r
JOIN cleaning_records c USING(report_id)
GROUP BY r.device_id, r.ts / 60;

CREATE INDEX idx_repair_device_hour
ON repair_uncertainty_analytics(device_id, hour_id);
